### ISSUE TITLE
El server me vota cada vez que entro

### ISSUE THREAD

**Issue by WolfFireMasterHD** [HeberonYT/APM5#1]
Yo abri  #el scrool del magicMC2 y me voto el server diciendo que hay un porblema interno del server , despues de que me salio eso volvi a entrar y pero no podia abrir nada ,  ## me doy cuenta de que parecia que era  problema de conexion, pense que el scrool que abri era el problema pero no me permite votarlo.
Esto fue ccerca de las 7:30 según la hora de Perú                        
Atte. WolfFireMasterHD

**Comment by HeberonYT** [comment]
Parece el mismo problema ya reportado #5 
Como mencioné, es bug del mod, no quiero retirarlo del modpack, así que la mejor opción es desactivar ese scroll para que no suceda a mas jugadores. 
@WolfFireMasterHD se ha eliminado el item de tu inventario, ya puedes entrar al servidor! :wink:
