### ISSUE TITLE
Parcela inactiva?

### ISSUE THREAD

**Issue by melohhh** [HeberonYT/APM5#11]
**Hola Heberon
hace mas de un mes q un amigo está esperando q se desclaimee la parcela de al lado de la mía, está inactiva desde hace muchísimo ( repito, mas de un mes)
podrías hacer algo al respecto?
no se si este post sea valido, lei q se podían postear cosas con respecto a las parcelas, así que intentando no pierdo nada.
tenés alguna forma de ver cuanto lleva inactiva? te dejo la id
ID: -10;4
Owner: Nico_12_
ojalá puedas hacer algo, muchas gracias. adiós.**

**Comment by HeberonYT** [comment]
Se ha eliminado la parcela.
Saludos!

**Comment by melohhh** [comment]
Mil gracias :D!!
