### ISSUE TITLE
reporte de crasheo

### ISSUE THREAD

**Issue by XxthekillercatxX** [HeberonYT/APM5#12]
entro al server me  crashea quiero solucion quiero entrar 

![mirar 2](https://cloud.githubusercontent.com/assets/24710215/21533027/59dca89a-cd35-11e6-994b-0c30c80f2a6f.PNG)

![mirar](https://cloud.githubusercontent.com/assets/24710215/21532971/ad82f6a8-cd34-11e6-8075-6ffd0f7096d6.PNG)

**Comment by HeberonYT** [comment]
Para ayudarte lee las instrucciones sobre como publicar un Crash Report.

**Comment by XxthekillercatxX** [comment]
no puedo entrar no me da tiempo a reaccionar nesecito entrar y que un admin omoderador me aga tp asia el
eso nescito o que quiten ese mod que me crashea

@HeberonYT

**Comment by XxthekillercatxX** [comment]
es nomas entrar y crashea @HeberonYT

**Comment by XxthekillercatxX** [comment]
@HeberonYT 

el mod statues es e que me causa el crasheo

**Comment by HeberonYT** [comment]
Solucionado.
