### ISSUE TITLE
Perdida de waipoints por error

### ISSUE THREAD

**Issue by javixd1** [HeberonYT/APM5#15]
Perdon por la molestia querido heberon soy Javier_Games_XD
hoy actualice apm5 sin serciorarme q la ultima ves mori en el server y tenia q recojer mis cosas q estaban en el cofre (me costo mucho conseguirlas)
al iniciar en la nueva actualizacion ya no abia los waypoints y lamentablemente perdi las cordenadas de la ultima muerte y los rastros de mi muerte trate de recuperar la vercion anterior pero nada ya no hay cordenadas :c y queria saber si por favor me ayudabas a llegar a el o si podias recuperar mis cosas espero no molestar mucho gracias de antemano 
Pd: el server es muy bueno gracias por crearlo soy y sub q no se pierde ni un video tuyo  XD gracias por la comprencion y  nuevamente mil disculpas

**Comment by HeberonYT** [comment]
Hola!
Los puntos del minimapa solo se guardan en tu carpeta .minecraft, no en el servidor, así que no puedo hacer nada para saber donde están tus cosas.
