### ISSUE TITLE
No me permite entrar ;(

### ISSUE THREAD

**Issue by Javaad07** [HeberonYT/APM5#17]
Instalé el launcher y luego añadí la ip del server pero a la hora de entrar sale esto

![problema](https://cloud.githubusercontent.com/assets/24866770/21583139/97bdd34a-d038-11e6-8e1a-bccac9adb05e.png)

![problema2](https://cloud.githubusercontent.com/assets/24866770/21583136/88b4d484-d038-11e6-8c0c-660d139ac3ce.png)

**Comment by HeberonYT** [comment]
Para entrar al servidor debes instalar el modpack especial para entrar, lo puedes descargar desde la web del server **`apm5.lesdm.com`**
