### ISSUE TITLE
Reporte A Jugador Que Me Mato En 2 Ocasiones 

### ISSUE THREAD

**Issue by CrisCraft504** [HeberonYT/APM5#19]
Reporto al usuario "RezaJr" por matarme en dos ocasiones usando Uranio, para describir un poco el caso, todo empezo una vez que estabamos varios jugadores en el mercado entonces el llego y tiro Uranio en el mercado donde estabamos nosotros, comenzamos a hacernos daño y yo hasta el momento no sabia que habia sido dicha cosa, dado que yo me he llevado bien en el servidor con el, me escribio por privado y me dijo que el habia sido y que lo habia hecho para que los demas se hicieran daño, yo le dije que no lo volviera a hacer, en otra ocasion llego a mi casa de nuevo y me tiro el Uranio y el llego con el traje que lo proteje le reclame de nuevo y le dije que a la proxima me iba a dejar matar solo para reportarlo porque su bromita es de mal gusto, no lo hice gracias al HoneyDrop la comida que da regeneracion pude salvarme, el caso es que cuando me mato yo estaba en el nether tan tranquilo consiguiendo cabezas de wither en un Spawn cuando el llego y me tiro Uranio otra vez y mori inmediatamente, el tambien murio con su misma  broma porque se le rompio el traje que a el lo proteje.

Aqui les dejo una captura como pueden ver me 117:22 de radicion algo que es imposible de aguantar y ahi fue donde mori por seguanda ocasion por su estupida broma ya estoy cansado de el espero que hagan algo, por suerte tengo testigos que vieron morirme :)
![2017-01-01](https://cloud.githubusercontent.com/assets/24880900/21595238/9ed274d8-d123-11e6-8368-315c05f57887.png)

**Comment by HeberonYT** [comment]
Se ha baneado al usuario.
