### ISSUE TITLE
mods

### ISSUE THREAD

**Issue by EnderHerobrina12** [HeberonYT/APM5#20]
hola heberon me gustaria que metieras mas mods como los que tiene vegeta se que hay mods que se bugean y no te dejan entrar por un fallo pero son mmuy pocos mods y los acabamos rápido y también me gustaría que reiniciara el atum por que no hay casi ninguna pirámide que no este hecha si pudiera meter los mods como el comes a live o el mod creatures me gustaría mucho sex que hay incompatibilidades pero si las arreglara seriamos gente la que viniera 
un saludo y adios

**Comment by RedstonCartagena** [comment]
Los mods que nose han metido dan muchos problemas de compatibilidad por eso no se meten ademas ocasinar lso varios crasheo que ves en la serie
