### ISSUE TITLE
End

### ISSUE THREAD

**Issue by EnderHerobrina12** [HeberonYT/APM5#21]
Hola yo entro en el end y intento cojer a patitas pero me dice que no se puede usar por que no tengo permiso también me pregunto site caes al vacío pierdes tus cosas

**Comment by HeberonYT** [comment]
Hola!
Gracias por tu reporte, ya se ha solucionado lo del End, deberías poder usar el equipaje sin problemas.
Sobre la caída, sí se pierden las cosas si caes al vació.
Saludos.
