### ISSUE TITLE
Láser minero

### ISSUE THREAD

**Issue by Carlos88876** [HeberonYT/APM5#22]
Es un item prohibido pero lo necesito en dos crafteos o la maquina en el mercado por un precio alto.
El láser minero está prohibido por generación de lag pero teniendo los martillos no lo entiendo por lo cual me gustaria que no estuviera baneado. ID: Carlos_888_

**Comment by RedstonCartagena** [comment]
ve a survival y craftealo alli

**Comment by HeberonYT** [comment]
Este ítem se puede craftear en el **`/warp survival`** pero no debes llevarlo a las parcelas o lo perderás.
Saludos!
