### ISSUE TITLE
crasheo

### ISSUE THREAD

**Issue by RedstonCartagena** [HeberonYT/APM5#25]
Hberon hoy habia colocado una tolva enciam de lavadora de herramientas y justo se crasheo el server y ahroa cuando entramos joss y yo se crasheo si peudes entrar y romper la tolva te lo agradeceria

**Comment by HeberonYT** [comment]
Hola!
Se ha solucionado el problema, y la maquina se desactivó para evitar conflictos futuros.
Saludos.

**Comment by RedstonCartagena** [comment]
pero yo tenia mi espda de monkey dentro de la maquina

sigue la maquina puesta


________________________________
De: HeberonYT <notifications@github.com>
Enviado: martes, 10 de enero de 2017 18:52
Para: HeberonYT/APM5
Cc: RedstonCartagena; Author
Asunto: Re: [HeberonYT/APM5] crasheo (#25)


Hola!
Se ha solucionado el problema, y la maquina se desactivó para evitar conflictos futuros.
Saludos.

-

**Comment by HeberonYT** [comment]
tu espada la deje en el cofre de arriba.
