### ISSUE TITLE
bug muerte the betweendlands.

### ISSUE THREAD

**Issue by ferxexes** [HeberonYT/APM5#27]
heberon buenas tardes.

como me lo solicitaste te pido revises mi usuario, ya que antier se quedo bugueado al momento de morir en la dimension the beetwenlands, cada que entro muero sin posibilidad de tparme, o de volar.

ya recibiste el video por twitter, sirequieres mayor informacion estoy al pendiente.

saludos

**Comment by HeberonYT** [comment]
Hola!
Gracias por escribir por este medio por que ya lo había olvidado.
Se te colocó en el spawn, ya puedes entrar nuevamente.

**Comment by ferxexes** [comment]
gracias
