### ISSUE TITLE
ResModerador

### ISSUE THREAD

**Issue by Simejaku** [HeberonYT/APM5#28]
Hola @HeberonYT  Mi nombre es Jacobo tengo 20 años mi nickname en el server es Simejaku 
la cuestión por la que te escribo es que me gustaría ser moderador en APM5, me gusta ayudar en lo que puedo a los demás usuarios del servidor, entiendo muy bien los mods del servidor por si alguien tiene algún problema con uno de ellos yo podría ayudarlo, también creo que al servidor le falta un poco de orden mientras tu no estas y yo podría ayudarte en ello, entro todos los días así que por eso no te preocupes, no abusaría de mi autoridad siempre haría lo que es correcto para el usuario, como se las reglas del servidor también conozco las reglas de un moderador. Gracias por tu atención Y espero tu respuesta 

-Simejaku-

**Comment by HeberonYT** [comment]
ok perfecto, solo envíame un mail a mi correo para mandarte una guía de comandos.
Saludos!

**Comment by HeberonYT** [comment]
Ya tengo tu correo, gracias
