### ISSUE TITLE
no me deja entrar

### ISSUE THREAD

**Issue by jose12342** [HeberonYT/APM5#29]
cuando pongi la ip me sale el server me dise algo de mod conexion perdida mod rechazos y salen numeros y nobres

**Comment by Simejaku** [comment]
Cual es tu nickname del server jose?

**Comment by jose12342** [comment]
dijo me da incopatibilidad con los mods ya ;(

**Comment by HeberonYT** [comment]
Eso significa que no estas utilizando el Modpack correcto para conectarte, y el texto de números y nombres son los mods que te faltan.
Para ingresar al server público, debes descargar y utilizar el modpack que está publicado en la web del server.

`http://www.lesdm.com/apm5/modpack.html`
