### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by JONO8A** [HeberonYT/APM5#31]
Mi amiga Jaks_xxx murió en el betweenlands y al reaparecer muere todo el rato e intentado ir donde ella y no funciona nada necesitamos ayuda

**Comment by ZerkexX** [comment]
ese bug ya a pasado espera a Heberon tiene que reiniciar a tu amiga por que se buguio

**Comment by HeberonYT** [comment]
Ese error es común al morir en esa dimensión pero parece ser bug del mod y puedo solucionarlo.
Tu amiga ya puede entrar.
Saludos!
