### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Zayrack** [HeberonYT/APM5#32]
Mori en los pasillos de las parcelas y no me deja abrir el cofre

**Comment by HeberonYT** [comment]
Menciona la ubicación de tu cofre para ayudarte.

**Comment by Zayrack** [comment]
el cofre esta al lado de mi plot

**Comment by Zayrack** [comment]
digo en frente de mi plot

**Comment by HeberonYT** [comment]
Hola!
Tus cosas se depositaron en un cofre que esta en la parte superior de tu casa.
