### ISSUE TITLE
Posible Bug - Aditional Pipes

### ISSUE THREAD

**Issue by mbedoya-dev** [HeberonYT/APM5#33]
Buenas Noches.

Soy el usuario TITAN mauriyi, tengo un inconveniente con las tuberías de teletransporte.
Solo me funcionan en la misma dimensión, no puedo enviar cosas del Survival a mi parcela o viceversa. No se si es un bug o si esto no es posible de realizar en el server.

Gracias.

**Comment by HeberonYT** [comment]
Es parte de su funcionamiento, no es bug.
