### ISSUE TITLE
Ayuda por favor TITAN

### ISSUE THREAD

**Issue by mbedoya-dev** [HeberonYT/APM5#34]
Buenas noches,

Mi usuario es mauriyi, tuve un pequeño problema, quise separar una plot, pero se me separaron todas y los cofres y todo estaba preciso en el camino y desapareció todo. Porfa si me pueden ayudar a dejar mi plot como estaba, gracias.

**Comment by HeberonYT** [comment]
Hola!
Lamentablemente no es posible volver atrás.
