### ISSUE TITLE
Tengo un pequeño problema con mi plot

### ISSUE THREAD

**Issue by Javaad07** [HeberonYT/APM5#35]
Hola, al entrar al server usé el comando "/plot auto" y me colocó en mi parcela pero tengo un cofre el cuál no puedo romper porqué yo no lo puse. El cofre ya estaba ahí cuando puse el comando y no sé como quitarlo ya qué está en el medio de mi parcela

**Comment by HeberonYT** [comment]
Cerraste el ticket, esto ya esta solucionado o aun no?
Para ayudarte menciona tu nick.

**Comment by Javaad07** [comment]
Todo listo, reinicié mi plot y todo solucionado. Gracias
