### ISSUE TITLE
me robaron

### ISSUE THREAD

**Issue by perezdn** [HeberonYT/APM5#37]
hola soy el titan perez_ aunq en la parcela pone dpn1985
esta mañana cuando he entrado me faltaban 5 cofres el contenido es lo de menos porque las cosas que tenian era diamantes esmeraldas y cosas para ayudar alos demas como a mi me ayudaron en  su momento
y luego en la parcela me falta una losa de ladrillo que limitan mi parcela con la calle.
y ya por ultimo no me funciona el comando /plot deny
espero su respuesta pronto

**Comment by HeberonYT** [comment]
Lo del robo se revisará aunque es difícil saberlo sin pruebas contundentes.
El comando funciona sin problemas y se recomienda utilizarlo para evitar futuros robos dentro de tu plot.
Para establecerlo universal debes escribir **`/plot deny *`** así nadie podrá entrar.

**Comment by perezdn** [comment]
Si lo entiendo que sea dificil saber quien a sido sin pruebas. 
Pero el comando tanbien lo pongo con el aterisco?

/plot deny * 
O 
/plot deny

**Comment by HeberonYT** [comment]
Si, con asterisco para que se impida a todos los usuarios del server, o puedes poner **`/plot deny nombre`** para impedir a un usuario especifico, pero los demás que no pongas aun podrán entrar.
