### ISSUE TITLE
Unir plots

### ISSUE THREAD

**Issue by mbedoya-dev** [HeberonYT/APM5#38]
Buenas noches,

Ya que el ticket que abri antes fue cerrado, 
Quería saber como puedo hacer para unir de nuevo mis plots, ya que no hay opción para hacerlo y en la página lo ofrecen al momento de venderte el TITAN, gracias.

Mi nick es mauriyi, soy TITAN y no quiero unir todas las parcelas, solamente quiero unir 4, pero el server no me deja unirlas.

También quiero reportar otros errores:
El comando /plot middle no funciona
El comando /plot biome tampoco funciona, de este no sé bien como se usa, pero al esribir /plot biome, me aparecen los nombre de los biomas y al escribir /plot biome y el nombre del bioma, me aparece un error.

**Comment by HeberonYT** [comment]
Hola!
Gracias por reportar, el comando **`/plot merge`** ahora funciona, al meter el comando debes estar de pie sobre tu parcela y estar mirando en la dirección de la otra parcela que deseas unir.

El comando **`/plot middle`** si funciona, debes escribirlo estando sobre tu parcela y te llevara al centro de tu plot.

El comando **`/plot biome OCEAN`** si funciona, igual debes estar sobre la plot a la que quieras cambiar el bioma, y el nombre del bioma debes escribirlo en MAYUSCULAS.

Si tienes mas dudas o problemas, por favor abre un nuevo ticket.
