### ISSUE TITLE
desaparicion de articulos de cofres o robo.

### ISSUE THREAD

**Issue by ferxexes** [HeberonYT/APM5#39]
heberon buenas tardes.

de tu apoyo para revisar que paso con los articulos que estaban dentro de 3 cofres en mi plot, son 3 de madera y 1 de hierro, desaparecieron cosas como perlas ender, la rematadora(espada), herramientas encantadas, y armas, y gran cantidad de objetos varios que recogi en la dungeon, hoy me volvi a conectar y los encontre vacios, te comento que nadie esta de invitado en mi plot y nadie tiene acceso, le reporte el caso a hebert y me dijo que te avisaria.

me ayudas por favor.
![2017-01-17_16 29 23](https://cloud.githubusercontent.com/assets/24999632/22043992/fc13ec66-dcd7-11e6-9c82-0fbde0a5d50f.png)
![2017-01-17_16 40 44](https://cloud.githubusercontent.com/assets/24999632/22043996/0024cb36-dcd8-11e6-8df2-cdba89ff7e26.png)

te agradezco.

**Comment by ferxexes** [comment]
lo olvide es del server de LESDM  saludos

**Comment by HeberonYT** [comment]
Esto debe ir en el foro de ese servidor.
