### ISSUE TITLE
al generarse el nuevo mundo se me bugeo

### ISSUE THREAD

**Issue by oliverdestructor** [HeberonYT/APM5#4]
al generarse el nuevo mundo se me bugeo y me caí del mundo cuando morí no tenia tumba al parece fue el 17/12 a las 10 de paraguay

**Comment by DanMXGamerPro** [comment]
A mi me paso igual pero solo puse /home en donde lo tenia y de la nada empece a caer pensé que era solo generación pero de repente empece a perder vida y morí por caer del mundo perdí todas mis cosas tochas que tenia

**Comment by HeberonYT** [comment]
Este problema no se puede replicar.
Por favor realizar un reporte con datos completos, Nick, mundo en donde sucedió, ubicación, observaciones, etc.
