### ISSUE TITLE
Bug spawn castillo de zombies

### ISSUE THREAD

**Issue by ferxexes** [HeberonYT/APM5#41]
El día de hoy como entro en Mtto el server de lesdm 2 , entre nuevamente al server de Apm5 y estaba jugando y me invitaron a matar zombies a un castillo en eso estaba matando demasiados ( cientos de ellos literal) se ve en las imágenes, y me mataron el 19/01/2017 a eso de las 9:30 a las 10:0, sin embargo mis cosas se perdieron o se buguearon, no sé si por el exceso de lag que generan esos zombies pero no tengo mis cosas. Si puedes ayudarme lo agradecería.

**Comment by ferxexes** [comment]
![img_3944](https://cloud.githubusercontent.com/assets/24999632/22135692/78f972aa-de95-11e6-9440-dcd22ee35c83.JPG)
![img_3946](https://cloud.githubusercontent.com/assets/24999632/22135690/78c3cfec-de95-11e6-8dfd-bdbbdce22873.JPG)
![img_3947](https://cloud.githubusercontent.com/assets/24999632/22135689/78c023d8-de95-11e6-96aa-9b1395cdc8de.JPG)
![img_3948](https://cloud.githubusercontent.com/assets/24999632/22135691/78d2afbc-de95-11e6-9a81-0c06e62301d4.JPG)

**Comment by HeberonYT** [comment]
Verifica en los alrededores de tu punto de muerte, incluso mas arriba o abajo, dependiendo del lugar.
Aveces las tumbas se generan a algunos bloques de distancia.

**Comment by HeberonYT** [comment]
Se reviso esa zona y ya no hay zombies, por favor tu verifica si esta tu tumba.

**Comment by ferxexes** [comment]
Heberon, gracias por tu respuesta, la busque pero no se generó además soy rango titán, y no están en mi inventario. será que me cambies estevrango al de lesdm la verdad estoy desde inicio de lesdm y me gusta si se puede te agradecería si no me avisas saludos
