### ISSUE TITLE
Sugerencias de mods

### ISSUE THREAD

**Issue by gabZ0** [HeberonYT/APM5#44]
Buenas Heberon y compañía, Mi nick es ZzZ_gabZ0_ZzZ bueno de lo que os quiero hablar es de que por mi parte el pack le faltan mods como el chaoscraft.
Podríais poner en Twitter una encuesta donde los jugadores de este mismo pack podrían poner los mods que les gustarían que metierais, por mi parte quisiera meter 4 mods: ChaosCraft, Gravitation Suite, Ores Spawn, NEVERMINE MOD. 

Muchas Gracias por todo el Staff sobre todo a ti Heberen por estos servidores dedicados.

**Comment by HeberonYT** [comment]
Hola!
Gracias por tu aporte, el modpack tiene menos mods debido a que no funcionan correctamente en servidor, ya sea que están bugeados, causan lag, violan protecciones etc.
Por otra parte, no se añadirán mods que no estén usándose dentro de la serie Oficial de APM para no perder la esencia.
Saludos.
