### ISSUE TITLE
Mi usuario esta bug no paro de morir

### ISSUE THREAD

**Issue by WillManAg** [HeberonYT/APM5#45]
Hola! Entré a la dimensión del árbol gigante que tiene cuatro portales verdes y me morí, al reaparecer morí instantáneamente, se ha bugeado mi personaje y cada vez que doy a reaparecer, reaparezco muerto en la coordenada z:0 x:0 y:78 de la dimensión esa. Mis amigos han entrado han llenado de bloques, con agua, han quitado todo alrededor y da igual siempre aparezco muero. Me dice un mensaje de que mi cama no está o algo así y no puedo escribir en el chat aunque le de rápido antes de morir, mando un mensaje y me dice que no puedo mandar mensajes en el chat. Me da igual que reinicien mi cuenta o lo que sea necesario para poder seguir jugando porque estoy muy viciado jeje. Espero que puedan ayudarme gracias besos xd

Nombre: Leyenda

**Comment by Simejaku** [comment]
Ya a varios le ah pasado lo mismo espera que heberon lo vea porque la unica forma de que vuelvas a entrar esque reinicien tu cuenta. 
Pon tu nickname completo 

Saludos :D

**Comment by WillManAg** [comment]
Me llamo Leyenda ya lo he dicho!

**Comment by WillManAg** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/25344893/22317654/8355d8ee-e375-11e6-9b13-a935d5dbf89d.png)

De verdad me quedo despierto hasta las 3 de la madrugada porque supongo que es una buena hora para latinoamericanos para estar y ayudarme y sigo igual enserio nadie se preocupa aquí por los problemas del servidor? seguro que para cobrar el dinero de los vips si que están a la orden del día.

**Comment by HeberonYT** [comment]
Hola
Gracias por tu reporte, ya se te ha movido de lugar.
