### ISSUE TITLE
urgente

### ISSUE THREAD

**Issue by perezdn** [HeberonYT/APM5#47]
el server se desconecta cada 2 miutos o menos 
solucionarlo lo antes posible jejejeje

**Comment by javixd1** [comment]
![2017-01-26_15 44 56](https://cloud.githubusercontent.com/assets/24836801/22349781/3e048e42-e3df-11e6-9010-c3a0a26993a1.png)

![2017-01-26_15 51 53](https://cloud.githubusercontent.com/assets/24836801/22349858/81a8b47a-e3df-11e6-82fe-07d9ce3be94b.png)

se conecta ivithebestyt se resetea el server ayuda!!!!!

**Comment by perezdn** [comment]
Y eso no tiene solicion alguna ?
Una pregunta para ser aministrador o moderador que tengo que hacer o que requisitos hay que complir?
Porque he visto a una persona robando los cofres de muerte que no eran suyos

Enviado desde mi iPhone

El 26 ene 2017, a las 21:55, javixd1 <notifications@github.com<mailto:notifications@github.com>> escribi?:


[2017-01-26_15 44 56]<https://cloud.githubusercontent.com/assets/24836801/22349781/3e048e42-e3df-11e6-9010-c3a0a26993a1.png>

[2017-01-26_15 51 53]<https://cloud.githubusercontent.com/assets/24836801/22349858/81a8b47a-e3df-11e6-82fe-07d9ce3be94b.png>

se conecta ivithebestyt se resetea el server ayuda!!!!!

-

**Comment by HeberonYT** [comment]
Ya fue solucionado, se debe a malas conexiones o configuraciones, si volviera a suceder por favor de reportar en un nuevo ticket.
