### ISSUE TITLE
item bugeado, se me cierra el juego

### ISSUE THREAD

**Issue by karmadx** [HeberonYT/APM5#5]
buenas noches heberon y staff, me encontraba esta noche en el nether, donde mate un boss del tragicMC un jarra para ser mas especifico, y me dropeo una quest del mismo mod, la quise abrir para descubrir la quest que daba y se me cerro el juego, imposibilitandome volve a entrar, se cierra cada vez que quiero entrar. mi nick en el juego es karmadx, pueden quitarme el item dell inventario? para asi poder volver a entrar, muchas gracias por su tiempo

**Comment by karmadx** [comment]
heberon tambien queria preguntar si sabes porque no se generan mas estructuras o dungeons del tragicMC en el overworld, desde que añadiste el biomes o`plenty

**Comment by HeberonYT** [comment]
@karmadx Gracias por tu reporte en este medio.
Se reviso tu problema y probablemente sea una incompatibilidad del mod, contiene varios bugs ya detectados pero se trata de mantener el mod.
Se eliminó de tu inventario el ítem bugeado y ya puedes entrar al server.

El tema de las estructuras deberá tratarse en otro tema por separado, pero te adelanto que seguramente se activaran nuevamente.
Saludos.
