### ISSUE TITLE
AYUDA

### ISSUE THREAD

**Issue by KleirRampage** [HeberonYT/APM5#51]
Mi nick dentro del juego es KleirRampage Tengo 22 años soy de paraguay bueno resulta el problema principal es que fui a la dimension del Portal en el arbol y Al aparecer apareci dentro de un bloque y quede bugeado perdiendo todoos mis itens armas todo... y quede bugeado aparezco y muero no puedo salir hacer tp o ir algun spawn estubo mirando Sumajuke algo asi xd y tambien algunos titans y no pudieron ayudarme me dijieron que usted heberon podria ayudarme si podria sacarme de ese bucle xfa... saludos

**Comment by HeberonYT** [comment]
Se te ha colocado en el Spawn, ya puedes ingresar, gracias por el reporte.
