### ISSUE TITLE
Bug me caigo de mundo

### ISSUE THREAD

**Issue by Carlos88876** [HeberonYT/APM5#53]
Es un bug por el que me cai del mundo y perdi todo lo que tenia y si pudiera romper la bedrock lo cojeria
![2017-01-28_23 34 39](https://cloud.githubusercontent.com/assets/24904462/22400358/b06a8430-e5b2-11e6-81b2-a5565c97364e.png)

**Comment by HeberonYT** [comment]
Ese problema a sucedido antes y por lo general se debe a la conexión entre tu Pc y el servidor, eso causa que el personaje caiga infinitamente.
Lamentablemente las cosas no se pueden recuperar, el punto de muerte dice que esta a 268m debajo de la roca base, por lo tanto nadie puede bajar sin morir, recuerda ademas que no se generan bloques mas abajo de ese nivel, así que seguramente no quedo ninguna tumba.

**Comment by Carlos88876** [comment]
Ok gracias.

**Comment by AlexanderJimenez** [comment]
Yo Tambien Me Mori Haci Pero Con Moderador Me Ayudó La cosa Me Apareció  En Un Barco Y Hay MucHO  Cofre..
