### ISSUE TITLE
juntar parcelas 

### ISSUE THREAD

**Issue by perezdn** [HeberonYT/APM5#55]
hola borre la parcela que tenia antes y ahora me gustaria que me juntaran estar parcelas 
-22;-4
-22;-5
-22;-6
-21;-4
-21;-5
-21;-6 
esas son las parcelas soy perez_ y soy titan muchas gracias por todo

**Comment by HeberonYT** [comment]
Hola, para juntar parcelas ya no es necesario pedirlo a un Admin, tu mismo lo puedes hacer, solo recuerda estar de pie sobre tu parcela y mirar en la direccion de la otra, los comandos tambien estan publicados en el servidor, **`/warp comandos`**
Saludos
