### ISSUE TITLE
reporte por robo

### ISSUE THREAD

**Issue by XxthekillercatxX** [HeberonYT/APM5#6]
![www](https://cloud.githubusercontent.com/assets/24710215/21416021/252c5d6c-c7ee-11e6-9318-1f0d3d3089ab.png)

![2016-12-22_01 55 06](https://cloud.githubusercontent.com/assets/24710215/21415910/35036650-c7ed-11e6-9b70-a14e46c075ca.png)
![2016-12-22_02 26 38](https://cloud.githubusercontent.com/assets/24710215/21416006/fc79c274-c7ed-11e6-9dc7-a3addca40f5e.png)

el presente día miércoles alas 2:00 hs argentina me a entrado una persona y me a roto la mitad de todos los cofres que tenia y las cosas que estaban dentro desaparecieron.

![2016-12-22_01 52 42](https://cloud.githubusercontent.com/assets/24710215/21415868/da9e88c0-c7ec-11e6-90ba-3a339cb136e5.png)
![2016-12-22_01 52 45](https://cloud.githubusercontent.co
![qqq](https://cloud.githubusercontent.com/assets/24710215/21415878/f247b686-c7ec-11e6-95c4-5f66bf7884f7.png)
![2016-12-22_01 55 06](https://cloud.githubusercontent.com/assets/24710215/21415890/038e65d4-c7ed-11e6-9c37-2c282657d1fc.png)

m/assets/24710215/21415869/daa3c128-c7ec-11e6-891a-d91df0a5d830.png)
Cuando me dí cuenta que los cofres estaban rotos lo que hice fue llamar a mi amigo RamaMoreno67 (que estaba jugando con él por Skype) para que me pueda ayudar a agarrar las cosas que estaban tiradas en el suelo en la entrada de mi parcela.

**Comment by HeberonYT** [comment]
Para realizar el reporte de robo, debes tener pruebas claras del ladrón, (si está dentro de tu plot o si lo menciona abiertamente por el chat) así se podrá imponer un castigo al usuario.
En este caso no se puede realizar ninguna acción y tampoco recuperar cosas perdidas debido a falta de comprobación.
Para evitar este tipo de problemas, se recomienda negar el acceso a tu plot con el comando:
` /plot deny *`
Este y otros comandos para seguridad los puedes encontrar dentro del servidor escribiendo:
`/warp comandos`
