### ISSUE TITLE
reporte 

### ISSUE THREAD

**Issue by XxthekillercatxX** [HeberonYT/APM5#8]
![2016-12-24_19 11 58](https://cloud.githubusercontent.com/assets/24710215/21468940/fc160d02-ca0d-11e6-9fbd-14383270f94e.png)

el usuario josegemer estubo insultando el chat por 2 horas. porfavor aser algo 

att:XxthekillercatxX

**Comment by HeberonYT** [comment]
Gracias por tu reporte, se ha baneado al usuario.
