### ISSUE TITLE
Report Spam

### ISSUE THREAD

**Issue by melohhh** [HeberonYT/APM5#9]
Usuario molesto.

![2016-12-24_19 31 44](https://cloud.githubusercontent.com/assets/24661589/21468964/0c5a2bb0-ca10-11e6-805b-acfa4ea7c15f.png)
![2016-12-24_19 30 15](https://cloud.githubusercontent.com/assets/24661589/21468966/11709af8-ca10-11e6-8a3f-2e578dac6f29.png)
![2016-12-24_19 28 23](https://cloud.githubusercontent.com/assets/24661589/21468972/17d87f46-ca10-11e6-85ff-6320652fac7b.png)
![2016-12-24_19 44 22](https://cloud.githubusercontent.com/assets/24661589/21468995/778e49f6-ca11-11e6-97ff-2022df4b3e51.png)
![2016-12-24_19 44 21](https://cloud.githubusercontent.com/assets/24661589/21468996/79279a74-ca11-11e6-9c04-05165d994fd3.png)
![2016-12-24_19 48 27](https://cloud.githubusercontent.com/assets/24661589/21469001/fb51ba2a-ca11-11e6-92aa-8d7c9f3061ec.png)

**Comment by HeberonYT** [comment]
Gracias por el reporte, ya fue baneado.
